### ISSUE TITLE
About using a better model

### ISSUE THREAD

**Issue by wing212** [voldemortX/DST-CBC#11] opened 2021-11-16 08:59 UTC
I would like to ask if you have used a better model for experimentation, such as deeplab V3+. Will it bring better accuracy if you use a better model?

**Comment by voldemortX** [comment] 2021-11-16 09:47
> I would like to ask if you have used a better model for experimentation, such as deeplab V3+. Will it bring better accuracy if you use a better model?

I would say it is highly likely we can get better performance with a better model.

However, when this work finished first draft (that's like early 2020), the SSS community commonly uses DeepLabV2 (if not only DeepLabV2). I never tried other models myself (I believe in SSL, absolute performance mean **little**, compared to gap to Oracle or Baseline), you are encouraged to try it though, I have some better segmentation models implemented in a similar style at https://github.com/voldemortX/pytorch-auto-drive.

**Comment by voldemortX** [comment] 2021-11-17 07:24
@wing212 Closing as a duplicate of #1.

**Closed by voldemortX** 2021-11-17 07:24 UTC

**Comment by wing212** [comment] 2021-11-17 07:33
Thank you for your reply, I will take a closer look
